### ISSUE TITLE
Cannot set the velocity directly on PassiveVehicle

### ISSUE THREAD

**Issue by Sonny22** [ricardojmendez/UnitySteer#29]
Hi :)
There is a small mistake/incoherence in PassiveVehicle.cs.
The Velocity property setter is defined to throw an exception if we attempt to modify the property. But I set that my vehicle cannot move and in the Update method it is stated if the vehicle cannot move then Velocity equal Vector3.zero. So each Update it is throwing an exception. 
Anyway great port of OpenSteer.
Thanks.

**Comment by ricardojmendez** [comment]
PassiveVehicle is not meant to set its own speed, merely to be detected (or potentially to report on it).
