### ISSUE TITLE
2D integration issues

### ISSUE THREAD

**Issue by LordSharpe** [ricardojmendez/UnitySteer#35]
Hello. I am planning on using UnitySteer as my primary pathing system for a 2D space shooter, specifically using Unity5 2D. Some issues I had to deal with, for future reference:

All rigid bodies and colliders use the 3D version only, not the 2D version (Rigidbody vs Rigidbody2d, Collider vs Collider2D). Had to go through and replace them, would be useful if this was an option.

Had to change the forward vector to up by default, since thats the Unity default. Theres a pending pull request that handles this well, as well as locking rotation axes. 

All behaviours are assumed to be on the gameObject on awake. This makes swapping steer behaviours out dynamically impossible withough having a pile of disabled steers cluttering up the prefabs. Minor issue.

 Additionally, modified the radars to store rigidbody ids instead of collider ids, but thats very specific to my game. Very simple to do.

**Comment by ricardojmendez** [comment]
Di you have a pull request for changes beyond #28? I'm unclear if it's a bug, a request for features or just a comment.

**Comment by LordSharpe** [comment]
I will eventually have a pull request for some of these, but currently just a comment.

**Comment by ricardojmendez** [comment]
Acknowledged @LordSharpe. Closing the issue since it doesn't require action, but will keep it around for the discussion. Cheers!
