### ISSUE TITLE
steer around a point

### ISSUE THREAD

**Issue by longvk1989** [ricardojmendez/UnitySteer#40]
Can you show me how to steer an object around a certain point?

**Comment by ricardojmendez** [comment]
It depends on what sort of behavior you want. Do you want the agent approaching the point, then always remaining at a certain distance? Approaching the point, then describing a circle around it at a certain radius? And then, If it is 3D space, you have to choose between a lot more than just "steering left or right".

I'd recommend you start by checking out the UnitySteerExamples project and going through them, those using SteerForTether will likely help you get started.
