### ISSUE TITLE
Automated deployment

### ISSUE THREAD

**Issue by GandaG** [ricardojmendez/UnitySteer#42]
While this wouldn't actually buld per se (though if it is actually possible distributing a dll is way better than a unity package with source code) some sort of continuous integration or at least automated deployment would be a huge help. (it would also help with the future docs)

**Comment by dh-nunes** [comment]
Actually I'd welcome some help GandaG/unityCItest#1 GandaG/unityCItest#2

**Comment by dh-nunes** [comment]
@ricardojmendez Here is a somewhat functional solution GandaG/unitypackage-ci#4. What do you think?

**Comment by ricardojmendez** [comment]
Hi @GandaG,

Will try to go over it early tomorrow, or if not I'll get back to you Monday - things are a bit hectic.

Thanks!

**Comment by dh-nunes** [comment]
@ricardojmendez Sure, take your time, there are still a few unexpected things I need to fix and it'll take some time. It should work reasonably well though.
