### ISSUE TITLE
Help with SteerForPathSimplified !!!

### ISSUE THREAD

**Issue by sangaloma** [ricardojmendez/UnitySteer#43]
Hi everybody,
This is the first time I am using unitysteer, i tried to use SteerForPathSimplified.cs but the problem that i wasnt able to assign the path to the script.
Can anyone help me with this?

**Comment by ricardojmendez** [comment]
Can you elaborate?  Your original post stated:

>  (i cant see a path variable in the inspector)

Path is not a serialized field that you can just assign in the inspector, you should set a pathway at runtime. How are you unable to assign the path?

**Comment by ricardojmendez** [comment]
Closing given the lack of extra details.
