### ISSUE TITLE
I'm not clearly understand what the IsPostProcess variable means.

### ISSUE THREAD

**Issue by zwxbest** [ricardojmendez/UnitySteer#53]
What flaw will occur if calculate all steering force together?
And what the IsPostProcess variable means?
I will greatly thank you if you can give me a tip.

**Comment by ricardojmendez** [comment]
> What flaw will occur if calculate all steering force together?

Could you clarify which comment or documentation bit are you referring to?

> And what the IsPostProcess variable means?

A post-processing behavior is one that is applied after all other forces have been calculated, so it can act on their overall result. As an example, see `SteerForSpeedFluctuation` or `SteerForTether`.

**Comment by zwxbest** [comment]
Thank you so much, now I understand it.
A post-processing behavior usally use Vehicle.DesiredVelocity in caluculation.

**Comment by ricardojmendez** [comment]
That is correct. That way it can apply any correction it want, or override it altogether because of its own criteria.

Cheers!
