### ISSUE TITLE
Basic vs Post-Processing behaviors

### ISSUE THREAD

**Issue by jhclaura** [ricardojmendez/UnitySteer#57]
First all, thank you so much for making + sharing UnitySteer!

I have question between Basic & Post-Processing behaviors, is Post-Processing behavior design to overwrite the Basic one?
In the funciont **_CalculateForces()_** of _**TickedVehicle.cs**_, the **adjustedVelocity** will overwrite **newVelocity** to be the **TargetSpeed**. So I'm just curious about the intention, and wondering if you have any tips to find the balance between different behaviors, or any resources about learning the theory. Thanks!

**Comment by jhclaura** [comment]
Found a good one by [Craig Reynolds](http://www.red3d.com/cwr/steer/)
(sorry I probably shouldn't post it here, just thought others might be interested to know)

**Comment by ricardojmendez** [comment]
Hi Laura,

You can find about post-processing behaviors on #53. I'll also look into an old article I had about it and re-post it on the site.

About the balance... it really depends on what you're aiming for.  Craig Reynolds' recommendations should definitely be taken as a canonical reference.

Cheers!

**Comment by jhclaura** [comment]
Thanks for the link! Much appreciated!
